added the source tracking
ColoredCow/civicrm pull request #16
Opened 2024-06-07 07:40 UTC by sameer-bot1

Here I added 
1. Custom field group  named as `Source Tracking`
2. Custom field named as  `Source`
3. Source field added to `Name and Address` profile

2024-06-07 07:47 UTC, pokhiii requested changes

2024-06-07 07:47 UTC, pokhiii commented on civicrm-2024-06-06-73231bd.sql
How is this file generated? It needs to be removed.

2024-06-07 07:47 UTC, pokhiii commented on wp-content/upgrade/civicrm-config-log/ConfigAndLog/.htaccess
This file is not needed can you remove it and add `wp-content/upgrade/` to `.gitignore`

2024-06-07 07:55 UTC, sameer-bot1 commented on civicrm-2024-06-06-73231bd.sql
ok sure

2024-06-08 09:37 UTC, pokhiii commented
Closing this as I have implemented this separately.

2024-06-08 09:37 UTC, closed without merging